# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages/events/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.messages.events import events_pb2 as messages_dot_events_dot_events__pb2
from app.messages.events.v1 import data_pb2 as messages_dot_events_dot_v1_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fmessages/events/v1/events.proto\x12\x12messages.events.v1\x1a\x1cmessages/events/events.proto\x1a\x1dmessages/events/v1/data.proto\"M\n\x0cSmsSubmitted\x12)\n\x03sms\x18\x01 \x01(\x0b\x32\x17.messages.events.v1.SmsR\x03sms:\x12\xba\xf8\xd8,\rsms_submittedB\x8f\x01\n\x16\x63om.messages.events.v1B\x0b\x45ventsProtoP\x01\xa2\x02\x03MEX\xaa\x02\x12Messages.Events.V1\xca\x02\x12Messages\\Events\\V1\xe2\x02\x1eMessages\\Events\\V1\\GPBMetadata\xea\x02\x14Messages::Events::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages.events.v1.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\026com.messages.events.v1B\013EventsProtoP\001\242\002\003MEX\252\002\022Messages.Events.V1\312\002\022Messages\\Events\\V1\342\002\036Messages\\Events\\V1\\GPBMetadata\352\002\024Messages::Events::V1'
  _SMSSUBMITTED._options = None
  _SMSSUBMITTED._serialized_options = b'\272\370\330,\rsms_submitted'
  _SMSSUBMITTED._serialized_start=116
  _SMSSUBMITTED._serialized_end=193
# @@protoc_insertion_point(module_scope)
