# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/messages/events/v1/events.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from app.messages.events import events_pb2 as app_dot_messages_dot_events_dot_events__pb2
from app.messages.events.v1 import data_pb2 as app_dot_messages_dot_events_dot_v1_dot_data__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#app/messages/events/v1/events.proto\x12\x16\x61pp.messages.events.v1\x1a app/messages/events/events.proto\x1a!app/messages/events/v1/data.proto\"O\n\x0bSmsReceived\x12-\n\x03sms\x18\x01 \x01(\x0b\x32\x1b.app.messages.events.v1.SmsR\x03sms:\x11\xba\xf8\xd8,\x0csms_received\"Q\n\x0cSmsSubmitted\x12-\n\x03sms\x18\x01 \x01(\x0b\x32\x1b.app.messages.events.v1.SmsR\x03sms:\x12\xba\xf8\xd8,\rsms_submitted\"G\n\x07SmsSent\x12-\n\x03sms\x18\x01 \x01(\x0b\x32\x1b.app.messages.events.v1.SmsR\x03sms:\r\xba\xf8\xd8,\x08sms_sent\"y\n\x13SmsCallbackReceived\x12\x46\n\x0csms_callback\x18\x01 \x01(\x0b\x32#.app.messages.events.v1.SmsCallbackR\x0bsmsCallback:\x1a\xba\xf8\xd8,\x15sms_callback_receivedB\xa4\x01\n\x1a\x63om.app.messages.events.v1B\x0b\x45ventsProtoP\x01\xa2\x02\x03\x41ME\xaa\x02\x16\x41pp.Messages.Events.V1\xca\x02\x16\x41pp\\Messages\\Events\\V1\xe2\x02\"App\\Messages\\Events\\V1\\GPBMetadata\xea\x02\x19\x41pp::Messages::Events::V1b\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'app.messages.events.v1.events_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\032com.app.messages.events.v1B\013EventsProtoP\001\242\002\003AME\252\002\026App.Messages.Events.V1\312\002\026App\\Messages\\Events\\V1\342\002\"App\\Messages\\Events\\V1\\GPBMetadata\352\002\031App::Messages::Events::V1'
  _SMSRECEIVED._options = None
  _SMSRECEIVED._serialized_options = b'\272\370\330,\014sms_received'
  _SMSSUBMITTED._options = None
  _SMSSUBMITTED._serialized_options = b'\272\370\330,\rsms_submitted'
  _SMSSENT._options = None
  _SMSSENT._serialized_options = b'\272\370\330,\010sms_sent'
  _SMSCALLBACKRECEIVED._options = None
  _SMSCALLBACKRECEIVED._serialized_options = b'\272\370\330,\025sms_callback_received'
  _SMSRECEIVED._serialized_start=132
  _SMSRECEIVED._serialized_end=211
  _SMSSUBMITTED._serialized_start=213
  _SMSSUBMITTED._serialized_end=294
  _SMSSENT._serialized_start=296
  _SMSSENT._serialized_end=367
  _SMSCALLBACKRECEIVED._serialized_start=369
  _SMSCALLBACKRECEIVED._serialized_end=490
# @@protoc_insertion_point(module_scope)
