# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: events/sms_submitted.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from data import sms_pb2 as data_dot_sms__pb2
from events import events_pb2 as events_dot_events__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1a\x65vents/sms_submitted.proto\x12\x11ujumbe.sms.events\x1a\x0e\x64\x61ta/sms.proto\x1a\x13\x65vents/events.proto\"N\n\x0cSmsSubmitted\x12*\n\x03sms\x18\x01 \x01(\x0b\x32\x18.ujumbe.sms.messages.SmsR\x03sms:\x12\xba\xf8\xd8,\rsms_submittedB\x90\x01\n\x15\x63om.ujumbe.sms.eventsB\x11SmsSubmittedProtoP\x01\xa2\x02\x03USE\xaa\x02\x11Ujumbe.Sms.Events\xca\x02\x11Ujumbe\\Sms\\Events\xe2\x02\x1dUjumbe\\Sms\\Events\\GPBMetadata\xea\x02\x13Ujumbe::Sms::Eventsb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'events.sms_submitted_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\025com.ujumbe.sms.eventsB\021SmsSubmittedProtoP\001\242\002\003USE\252\002\021Ujumbe.Sms.Events\312\002\021Ujumbe\\Sms\\Events\342\002\035Ujumbe\\Sms\\Events\\GPBMetadata\352\002\023Ujumbe::Sms::Events'
  _SMSSUBMITTED._options = None
  _SMSSUBMITTED._serialized_options = b'\272\370\330,\rsms_submitted'
  _SMSSUBMITTED._serialized_start=86
  _SMSSUBMITTED._serialized_end=164
# @@protoc_insertion_point(module_scope)
