# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/sms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from data import sms_status_pb2 as data_dot_sms__status__pb2
from data import sms_response_pb2 as data_dot_sms__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x64\x61ta/sms.proto\x12\x13ujumbe.sms.messages\x1a\x15\x64\x61ta/sms_status.proto\x1a\x17\x64\x61ta/sms_response.proto\"\xfd\x01\n\x03Sms\x12\x0e\n\x02id\x18\x01 \x01(\tR\x02id\x12\x1b\n\x06sender\x18\x02 \x01(\tH\x00R\x06sender\x88\x01\x01\x12\x1c\n\trecipient\x18\x03 \x01(\tR\trecipient\x12\x18\n\x07message\x18\x04 \x01(\tR\x07message\x12\x36\n\x06status\x18\x05 \x01(\x0e\x32\x1e.ujumbe.sms.messages.SmsStatusR\x06status\x12\x41\n\x08response\x18\x06 \x01(\x0b\x32 .ujumbe.sms.messages.SmsResponseH\x01R\x08response\x88\x01\x01\x42\t\n\x07_senderB\x0b\n\t_responseB\x91\x01\n\x17\x63om.ujumbe.sms.messagesB\x08SmsProtoP\x01\xa2\x02\x03USM\xaa\x02\x13Ujumbe.Sms.Messages\xca\x02\x13Ujumbe\\Sms\\Messages\xe2\x02\x1fUjumbe\\Sms\\Messages\\GPBMetadata\xea\x02\x15Ujumbe::Sms::Messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data.sms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ujumbe.sms.messagesB\010SmsProtoP\001\242\002\003USM\252\002\023Ujumbe.Sms.Messages\312\002\023Ujumbe\\Sms\\Messages\342\002\037Ujumbe\\Sms\\Messages\\GPBMetadata\352\002\025Ujumbe::Sms::Messages'
  _SMS._serialized_start=88
  _SMS._serialized_end=341
# @@protoc_insertion_point(module_scope)
