# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: data/sms_status.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x64\x61ta/sms_status.proto\x12\x13ujumbe.sms.messages*\xab\x01\n\tSmsStatus\x12\x0c\n\x08\x41\x43\x43\x45PTED\x10\x00\x12\r\n\tSCHEDULED\x10\x01\x12\x0c\n\x08\x43\x41NCELED\x10\x02\x12\n\n\x06QUEUED\x10\x03\x12\x0b\n\x07SENDING\x10\x04\x12\x08\n\x04SENT\x10\x05\x12\n\n\x06\x46\x41ILED\x10\x06\x12\r\n\tDELIVERED\x10\x07\x12\x0f\n\x0bUNDELIVERED\x10\x08\x12\r\n\tRECEIVING\x10\t\x12\x08\n\x04READ\x10\n\x12\x0b\n\x07PENDING\x10\x0b\x42\x97\x01\n\x17\x63om.ujumbe.sms.messagesB\x0eSmsStatusProtoP\x01\xa2\x02\x03USM\xaa\x02\x13Ujumbe.Sms.Messages\xca\x02\x13Ujumbe\\Sms\\Messages\xe2\x02\x1fUjumbe\\Sms\\Messages\\GPBMetadata\xea\x02\x15Ujumbe::Sms::Messagesb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'data.sms_status_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\027com.ujumbe.sms.messagesB\016SmsStatusProtoP\001\242\002\003USM\252\002\023Ujumbe.Sms.Messages\312\002\023Ujumbe\\Sms\\Messages\342\002\037Ujumbe\\Sms\\Messages\\GPBMetadata\352\002\025Ujumbe::Sms::Messages'
  _SMSSTATUS._serialized_start=47
  _SMSSTATUS._serialized_end=218
# @@protoc_insertion_point(module_scope)
