"""audit log

Revision ID: ac52bb38b7cf
Revises:
Create Date: 2020-07-01 18:13:18.504487

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.orm import sessionmaker

Session = sessionmaker()


# revision identifiers, used by Alembic.
revision = "ac52bb38b7cf"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    session = Session(bind=bind)

    with open("migrations/sql/audit_log.sql") as f:
        sql = f.read()
        session.execute(sql)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
