apiVersion: apps/v1
kind: Deployment
metadata:
    name: sms-api
    namespace: comms
    labels: &smsLabels
        app: sms
        tier: backend
        role: communication
        component: sms
spec:
    selector:
        matchLabels: *smsLabels
    replicas: 1
    template:
        metadata:
            labels: *smsLabels
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 3000
                fsGroup: 2000

            containers:
                -   name: sms-gateway
                    image: garihublimited/sms-gateway:latest
                    imagePullPolicy: Always
                    readinessProbe:
                        httpGet:
                            path: /health
                            port: 5000
                    ports:
                        - name: http
                          containerPort: 5000
                    env:
                        -   name: FLASK_ENV
                            value: "staging"

                        -   name: PORT
                            value: "5000"

                        -   name: SMS_TOKEN
                            valueFrom:
                                secretKeyRef:
                                    name: sms-config
                                    key: token

                        -   name: SMS_API_URL
                            valueFrom:
                                secretKeyRef:
                                    name: sms-config
                                    key: apiUrl

                        -   name: BROKER_USER
                            valueFrom:
                                secretKeyRef:
                                    name: sms-broker-credentials
                                    key: user

                        -   name: BROKER_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: sms-broker-credentials
                                    key: password

                        -   name: BROKER_HOST
                            value: 'rabbitmq-svc-headless'

                        -   name: BROKER_URL
                            value: 'amqp://$(BROKER_USER):$(BROKER_PASSWORD)@$(BROKER_HOST):5672//'
                        
                        - name: RESULT_BACKEND_HOST
                          value: redis-svc-headless

                        -   name: RESULT_BACKEND
                            value: 'redis://$(RESULT_BACKEND_HOST):6379'
