apiVersion: apps/v1
kind: Deployment
metadata:
    name: sms-api
    namespace: comms
    labels: &smsLabels
        app: sms
        tier: backend
        role: communication
        component: sms
spec:
    selector:
        matchLabels: *smsLabels
    replicas: 1
    template:
        metadata:
            labels: *smsLabels
        spec:
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
                runAsGroup: 3000
                fsGroup: 2000

            containers:
                -   name: sms-gateway
                    image: garihublimited/sms-gateway:latest
                    imagePullPolicy: Always
                    readinessProbe:
                        httpGet:
                            path: /health
                            port: 4000
                    ports:
                        -   containerPort: 4000
                    env:
                        -   name: FLASK_ENV
                            value: "staging"
                        -   name: PORT
                            value: "4000"

                        -   name: SMS_TOKEN
                            valueFrom:
                                secretKeyRef:
                                    name: sms-config
                                    key: token

                        -   name: SMS_API_URL
                            valueFrom:
                                secretKeyRef:
                                    name: sms-config
                                    key: apiUrl

                        -   name: BROKER_USER
                            valueFrom:
                                secretKeyRef:
                                    name: sms-amqp-credentials
                                    key: user

                        -   name: BROKER_PASSWORD
                            valueFrom:
                                secretKeyRef:
                                    name: sms-amqp-credentials
                                    key: password

                        -   name: BROKER_HOST
                            value: 'rabbitmq-discovery'

                        -   name: BROKER_URL
                            value: 'amqp://$(AMQP_USER):$(AMQP_PASSWORD)@$(BROKER_HOST):5672//'

                        -   name: RESULT_BACKEND
                            value: 'redis://redis:6379'
