name: Lint

on: [ push ]

permissions:
    contents: read
    pull-requests: read

jobs:
    lint:
        name: Lint
        runs-on: ubuntu-latest
        strategy:
            max-parallel: 4
            matrix:
                python-version: [ '3.10' ]

        steps:
            -   uses: actions/checkout@v3

            -   name: Set up Python ${{ matrix.python-version }}
                uses: actions/setup-python@v2
                with:
                    python-version: ${{ matrix.python-version }}

            -   name: Install Dependencies
                run: |
                    pip install poetry
                    poetry install

            -   name: Run Linting
                run: make lint
